
CREATE TABLE Locations (
	location_id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	address TEXT,
	city VARCHAR(100),
	state VARCHAR(100),
	country VARCHAR(100),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
